# Generated by Django 5.1.7 on 2025-03-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
